version: "3.8"
services:
  pipeline:
      container_name: pipeline
      image: blackdereker/jenkins:latest
      ports:
        - "8080:8080"
      environment:
        JAVA_OPTS: -Djenkins.install.runSetupWizard=false
        JENKINS_OPTS: --argumentsRealm.roles.user=admin --argumentsRealm.passwd.admin=admin --argumentsRealm.roles.admin=admin
      volumes:
        - ./jenkins_home:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
        - ./target:/target